Bombs functionality
TalPat/Bomberman pull request #31
Opened 2019-08-19 15:36 UTC by charlchi

Bombs detonate, create flames in a list and on the map, and also propagate.

2019-08-19 17:50 UTC, WSeegers requested changes
If you could add the prevention of propagation this would be complete and we can start looking at the next feature.

2019-08-19 17:50 UTC, WSeegers commented on models/src/Bombs.cpp
> +            for (int i = 1; i < BOMB_RANGE + 1; ++i)
I really like this solution, the only issue is that you are piercing. Please add some logic to prevent the propagation through solids

2019-08-20 12:00 UTC, WSeegers approved these changes
I feel this should be merged. A ticket has been opened for the prevention of propagation of destructible.
#33

2019-08-20 13:28 UTC, agabrie reviewed
change line 70 statement to
"if (tile == Tile::Destructible || tile == Tile::Solid)"

will stop flames from being generated beyond a indestructible wall

2019-08-20 13:40 UTC, charlchi commented
> change line 70 statement to
> "if (tile == Tile::Destructible || tile == Tile::Solid)"
> 
> will stop flames from being generated beyond a indestructible wall

Good point, added the change

2019-08-21 09:54 UTC, WSeegers approved these changes
Looks good closes

2019-08-21 11:37 UTC, agabrie approved these changes

2019-08-21 12:05 UTC, merged