Agabrie
TalPat/Bomberman pull request #38
Opened 2019-08-21 07:08 UTC by agabrie

2019-08-21 08:50 UTC, TalPat reviewed
Maybe merge your branch with master first then resolve conflicts, then redo the pull request?

2019-08-21 09:48 UTC, WSeegers commented
The pull request will be updated if you fix your branch. Merge master

2019-08-21 12:41 UTC, charlchi commented
@agabrie While in your `agabrie` branch, do a `git pull https://github.com/TalPat/Bomberman.git master`. All the conflicts should be resolved automatically and we can merge this.

2019-08-21 13:12 UTC, charlchi approved these changes

2019-08-21 15:41 UTC, WSeegers requested changes
Remove the .DS_Store(s) and add this to the .gitignore.
Clean up the the debug comments please.

2019-08-21 15:41 UTC, WSeegers commented on models/src/Enemy.cpp
> +	// std::cout << num <<"\n";
Remove all these commented debug statements.

2019-08-22 10:01 UTC, WSeegers commented on models/src/Enemy.cpp
> +	// std::cout << num <<"\n";
models/.DS_Store still exists

2019-08-22 10:02 UTC, WSeegers requested changes
Remove ```models/.DS_store```

2019-08-23 08:44 UTC, WSeegers reviewed
Looks good

2019-08-23 08:44 UTC, WSeegers approved these changes

2019-08-23 08:44 UTC, merged